/*******************************************************************************
 * Copyright 2022 Dell Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 *******************************************************************************/

package documents

import (
	"github.com/oklog/ulid/v2"
	"github.com/project-alvarium/alvarium-sdk-go/pkg/contracts"
	"github.com/project-alvarium/scoring-apps-go/pkg/policies"
	"math"
	"time"
)

const (
	EdgeLineage       string = "lineage"
	EdgeScoring       string = "scoring"
	EdgeTrust         string = "trust"
	VertexAnnotations string = "annotations"
	VertexData        string = "data"
	VertexScores      string = "scores"
)

// Data represents a document in the "data" vertex collection
type Data struct {
	Key       string    `json:"_key,omitempty"`      // Key uniquely identifies the document in the database
	Timestamp time.Time `json:"timestamp,omitempty"` // Timestamp indicates when the document was created
}

// Annotation represents a document in the "annotation" vertex collection
type Annotation struct {
	Key         string             `json:"_key,omitempty"`      // Key uniquely identifies the document in the database
	DataRef     string             `json:"dataRef,omitempty"`   // DataRef points to the key of the data being annotated
	Hash        contracts.HashType `json:"hash,omitempty"`      // Hash identifies which algorithm was used to construct the hash
	Host        string             `json:"host,omitempty"`      // Host is the hostname of the node making the annotation
	Kind        string             `json:"type,omitempty"`      // Kind indicates what kind of annotation this is. Defined as string to allow for annotation types outside of the Alvarium Go SDK
	Signature   string             `json:"signature,omitempty"` // Signature contains the signature of the party making the annotation
	IsSatisfied bool               `json:"isSatisfied"`         // IsSatisfied indicates whether the criteria defining the annotation were fulfilled
	Timestamp   time.Time          `json:"timestamp,omitempty"` // Timestamp indicates when the annotation was created
}

// NewAnnotation will map an Alvarium SDK annotation into an Annotation document
func NewAnnotation(a contracts.Annotation) Annotation {
	return Annotation{
		Key:         a.Id.String(),
		DataRef:     a.Key,
		Hash:        a.Hash,
		Host:        a.Host,
		Kind:        string(a.Kind),
		Signature:   a.Signature,
		IsSatisfied: a.IsSatisfied,
		Timestamp:   a.Timestamp,
	}
}

// Score represents a document in the "score" vertex collection
type Score struct {
	Key        ulid.ULID `json:"_key,omitempty"`       // Key uniquely identifies the document in the database
	DataRef    string    `json:"dataRef,omitempty"`    // DataRef points to the key of the data being annotated
	Passed     int       `json:"score,omitempty"`      // Passed indicates how many of the annotations for a given dataRef were Satisfied
	Count      int       `json:"count,omitempty"`      // Count indicates the total number of annotations applicable to a dataRef
	Policy     string    `json:"policy,omitempty"`     // Policy will indicate some version of the policy used to calculate confidence
	Confidence float64   `json:"confidence,omitempty"` // Confidence is the percentage of trust in the dataRef
	Timestamp  time.Time `json:"timestamp,omitempty"`  // Timestamp indicates when the score was calculated
}

func NewScore(dataRef string, annotations []Annotation, policy policies.DcfPolicy) Score {
	// Assuming "layer" is added to the Annotation type, it's easy enough to populate a "layer" property
	// on the Score type. The same applies w/r/t the proposed "tag" property.
	// All annotations in the incoming slice will be of the same kind.

	// However if the annotations are at the "app" layer, there needs to be knowledge to incorporate the
	// product of (cicd * osscore). This will require two queries:
	// 1.) Find the score at layer "cicd" with score.tag == annotation.Tag of "<commit-sha>".
	// 2.) Find the score at layer "os" with score.tag == annotation.Tag of "<vm-host-name>"

	// A score for cicd is generated by a build pipeline and is itself not necessarily linked to an OS Score.
	// It could be when an orchestrator deploys a workload to a given VM. Or possibly it's never linked
	// to anything but scores at the "app" layer. App layer scores might tie together cicd and OS/host scores.
	// If that were the case, then the imageTag facilitates the link from app to cicd scores. The hostname
	// available in the environment (perhaps passed from the VM into a container via env var) is already part
	// of the annotation and is applicable to both the OS (VM) and physical host layers, reflecting the imageTag
	// in the app and cicd layers.

	// Looking forward, if this method is asked to score a node at the app layer, in our first phase it would lookup
	// the cicd score via the imageTag. In a future phase, it would look up the VM/OS score via Hostname.

	// Similar knowledge applies to constructing the relevant edge in the graph
	var totalWeight, passedWeight float32
	var passed int
	for _, a := range annotations {
		w := policy.FetchWeight(a.Kind)
		totalWeight += float32(w.Value)
		if a.IsSatisfied {
			passed++
			passedWeight += float32(w.Value)
		}
	}

	confidence := float64(passedWeight / totalWeight)
	confidence = math.Round(confidence*100) / 100

	s := Score{
		Key:        NewULID(),
		DataRef:    dataRef,
		Passed:     passed,
		Count:      len(annotations),
		Policy:     policy.Name,
		Confidence: confidence,
		Timestamp:  time.Now(),
	}
	return s
}

// Trust represents a document in the "trust" edge collection
type Trust struct {
	From string `json:"_from"`
	To   string `json:"_to"`
}

// Lineage represents a document in the "lineage" edge collection
type Lineage struct {
	From string `json:"_from"`
	To   string `json:"_to"`
}

// Scoring represents a document in the "scoring" edge collection
type Scoring struct {
	From string `json:"_from"`
	To   string `json:"_to"`
}
